#################################################################
# ECEn 427 | Wave Converter
# @author Luke Hsiao
# @date 25 Oct 2014
#################################################################
CC = gcc

waveConvertermake:
	$(CC) waveConverter.c
	
clean:
	rm -f a.out
