/**
 *  This file contains all of the output sounds for Space Invaders as
 *  generated by waveConverter.c.  Note that waveConverter just appends
 *  arrays on, and this file will be corrupted if it is run more than once.
 *
 *  author: Luke Hsiao & Jeff Ravert
 *  25 October 2014
 */
/* Sound Declarations */

