
/**
 *  WaveConverter takes in a WAV file and outputs a
 *  C Source file containing the data as an int array
 *  This means that we will need to extern the variables
 *
<<<<<<< HEAD
 *  Note this only supports non-compressed wav files of 8-bit samples
=======
 *  Note this only supports non-compressed wav files
>>>>>>> 66f588297fffdadfb7027848b54b021e8a3c0e47
 *  author: Luke Hsiao & Jeff Ravert
 *  25 October 2014
 */

#include <stdio.h>
//#include <libsndfile.h>
#include "waveConverter.h"


FILE* input;
FILE* output;

void writeHeader() {
    fprintf(output, "/**\n");
    fprintf(output, " * This file contains all of the output sounds for Space Invaders as\n");
    fprintf(output, " * generated by waveConverter.c\n\n");
    fprintf(output, " * author: Luke Hsiao & Jeff Ravert\n");
    fprintf(output, " * 25 October 2014\n");
    fprintf(output, " */\n\n\n");
}

u32 chunkID;
u32 isDataChunk = FALSE;
u32 numSamples;
u32 sampleRate;
u8 tempData;
u16 bitsPerSample;

int main(int argc, char *argv[]) {

    
    if (argc != 3) { /* We're always expecting two arguments */
        printf("Usage: waveConverter [inputWAV] [nameOfSound]\n\n");
    }
    else {
        // argv[1] should be filename to open
        input = fopen(argv[1], "rb");


        // argv[2] is the name of the sound (e.g. alienSound1)
        char* soundName = argv[2];

        /* FOpen returns 0 on failer */
        if (input == 0) {
            printf("Could not open %s\n", argv[1]);
        }
        else {
            output = fopen("spaceInvadersSounds.c", "w+");

            if (output == 0) {
                printf("Error opening output: Check spaceInvadersSounds.c");
            }
            else {
                writeHeader();
                // Parse the WAV file here
                while(!isDataChunk) {
                    fread(&(chunkID), sizeof(int), 1, input);  
                    printf("chunkID: %x\n", chunkID);
                    
                    switch (chunkID) {
                        // Extract the sample rate
                        case FORMAT:
                            //Advance reader past formatsize, format, channels
                            fread(&(sampleRate), sizeof(int), 1, input);
                            fread(&(sampleRate), sizeof(int), 1, input);
                            fread(&(sampleRate), sizeof(int), 1, input);
                            printf("    Sample Rate: %d\n", sampleRate);
                            
                            // Advance to bits per sample
                            fread(&(bitsPerSample), sizeof(u16), 3, input);
                            fread(&(bitsPerSample), sizeof(u16), 1, input);
                            printf("    Bits per Sample: %d\n", bitsPerSample);
                            break;                            
                        // Extract actual data
                        case DATA:
                            fprintf(output, "int %s_soundData[] = {\n    ", soundName);
                            // Store number of samples
                            fread(&(numSamples), sizeof(int), 1, input);
                            printf("    Number of Samples: %d\n", numSamples);
                            // Parse Data
                            int i;
                            for (i = numSamples; i > 1; i--) {
                                if (i % 10 == 0) {
                                   fprintf(output, "\n    ", tempData); 
                                }
                                fread(&(tempData), sizeof(u8), 1, input);
                                fprintf(output, "%d,", tempData);
                            }
                            fread(&(tempData), sizeof(u8), 1, input); 
                            fprintf(output, "%d};\n", tempData);

                   
                            if (chunkID == DATA) {
                                isDataChunk = TRUE;
                            }
                            break;
                        default:
                            // Do nothing
                            break;
                    }
                }
                
                fprintf(output, "int %s_numberOfSamples = %d\n",soundName,numSamples);
                fprintf(output, "int %s_sampleRate = %d\n",soundName,sampleRate);
                
            }
        }        
    }
} /* End of MAIN */
